export enum EFFECT {
    REMOVE_POOL,
    REMOVE_COMPONENT,
    RAISE_ATTRIBUTE,
    LOWER_ATTRIBUTE,
    RAISE_POOL_CAPACITY,
    LOWER_POOL_CAPACITY,
    BONUS_POOL_QUANTITY,
    REGEN_POOL,
    DRAIN_POOL,
}
